name: metodoloit
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: 0.5.2
  firebase_auth: 0.18.3
  advance_pdf_viewer: ^1.2.1+2
  shared_preferences: ^0.5.12+4
  splashscreen: ^1.3.5





dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:
  uses-material-design: true

  assets:
    - images/metodolit_copy.png
    - images/Logoscuro.png
    - images/rotonda.png
    - images/logoscuro2.png
    - images/test3.png
    - images/check1.jpg
    - images/check0.jpg
    - filepdf/Introduzione_copy.pdf
    - filepdf/Modulo0.pdf
    - filepdf/Modulo1.pdf
    - filepdf/Modulo2.pdf
    - filepdf/Modulo3.pdf
    - filepdf/Modulo4.pdf
    - filepdf/Modulo5.pdf
    - filepdf/Modulo6.pdf
    - filepdf/Modulo7.pdf
    - filepdf/Modulo8.pdf
    - filepdf/Modulo9.pdf
    - filepdf/Modulo10.pdf
    - images/istruzioni.jpg
    - images/image.png
    - images/image1.png
    - images/vez.png
    - images/ciao2.png
    - images/cerchio1.png



  fonts:
    - family: OpenSans, SourceSansPro, FrankRhuhlLibre
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/FrankRuhlLibre-Regular.ttf




